export default {
    testEnvironment: 'node',
    coverageDirectory: 'coverage',
    collectCoverageFrom: [
        'controllers/**/*.js',
        'services/**/*.js',
        'models/**/*.js',
        'middlewares/**/*.js',
        'utils/**/*.js',
        '!**/node_modules/**',
        '!**/tests/**',
    ],
    coverageThreshold: {
        global: {
            branches: 70,
            functions: 70,
            lines: 70,
            statements: 70,
        },
    },
    testMatch: ['**/tests/**/*.test.js'],
    testTimeout: 60000,
    setupFilesAfterEnv: ['<rootDir>/tests/setup.js'],
    verbose: true,
    forceExit: true,
    clearMocks: true,
    resetMocks: true,
    restoreMocks: true,
    injectGlobals: true,
    transform: {},
    moduleFileExtensions: ['js', 'json', 'jsx', 'ts', 'tsx', 'node'],
    resolver: '<rootDir>/jest.resolver.cjs',
};
